# Generated by Django 4.0.4 on 2022-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_userlist_delete_regform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='firstName',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='lastName',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='password2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
