# Generated by Django 4.0.4 on 2022-07-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_userlist_email_alter_userlist_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='user_id',
        ),
    ]
