# Generated by Django 4.0.4 on 2022-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_course_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseCredits',
            field=models.IntegerField(),
        ),
    ]
