# Generated by Django 4.0.4 on 2022-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_course_coursecredits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modules', models.CharField(max_length=30)),
                ('Units', models.CharField(max_length=30)),
                ('Text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseCredits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseImage',
            field=models.ImageField(upload_to='media'),
        ),
    ]
