# Generated by Django 4.0.4 on 2022-08-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_components_alter_course_coursecredits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='component',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cms.course'),
            preserve_default=False,
        ),
    ]
