# Generated by Django 4.0.4 on 2022-08-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_components_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.course'),
        ),
    ]
