# Generated by Django 4.0.4 on 2022-08-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_components_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='components',
            name='Units',
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Units', models.CharField(max_length=30)),
                ('Text', models.TextField()),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.course')),
            ],
        ),
    ]
