# Generated by Django 4.0.4 on 2022-08-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_remove_components_text_remove_components_units_units'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='ModelUnits',
        ),
        migrations.AlterField(
            model_name='modelunits',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.components'),
        ),
    ]
