# Generated by Django 4.0.4 on 2022-08-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_modelunits_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='component',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='modelunits',
            old_name='unit',
            new_name='Module',
        ),
    ]
